---
# title: Markdownlint rules configuration
# authors:
#   - Steffen Klug <steffen.klug@de.bosch.com>
# date: 2023-02-16
# keywords: [infrastructure, linting]
# comment: |
#   Markdownlint configuration definition
# ---

# Example markdownlint YAML configuration with all properties set to their default value
# ------------------------------------------------------------------------------
# List of deviations from the default:
# - MD010 Hard Tabs in code blocks has been disabled
# ------------------------------------------------------------------------------

# Default state for all rules
default: true

# Path to configuration file to extend
extends: null

# MD010/no-hard-tabs - Hard tabs
MD010:
  # Include code blocks
  code_blocks: false
  # Fenced code languages to ignore
  ignore_code_languages: []
  # Number of spaces for each hard tab
  spaces_per_tab: 1
