---
# title: YAMLlint rules configuration
# author:
#   - Steffen Klug <steffen.klug@de.bosch.com>
# date: 2023-02-16
# keywords: [infrastructure, linting]
# comment: |
#   All yaml files linter extensions need to be added below
# ---

extends: default

rules:
  # Use only two spaces for intendation
  indentation:
    spaces: 2
  # Relax-line length into warning
  line-length:
    max: 120
    level: warning
